# ETAPA 1

## Dados Numéricos

In [94]:
# Variável Inteira
a = 1
print ('Valor de a = '+str(a))
type (a)
# a recebe valor de 1 e é uma variável inteira

Valor de a = 1


int

In [95]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)
# b recebe valor de 1.0 e é uma variavel do tipo float (maior precisão)

1.0


float

In [96]:
# Converter float para int
c = int(b)
print(c)
type(c)
#usando comando int para transformar variável float em int

1


int

In [97]:
# Declarando nan
import numpy as np
d = np.nan
print(d)
type(d)
#importando a biblioteca de arrays numpy

nan


float

In [98]:
#Operação com NaN
e = d*1
print(e)
e=d+1
print(e)
e=np.nansum([d,1])
print(e)
#primeiro é feita uma copia da matriz d
#aumentando 1 em cada valor da matriz d
#também soma 1 a cada elemento só que desconsiderando os valores nan da matriz

nan
nan
1.0


## Dados de texto

In [99]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)
# variáveis do tipo texto ficam entre aspas simples

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [100]:
a==1
# sinal de igual é representado por ==

True

In [101]:
h = (a==1)
print(h)
type(h)
# 1 é true

True


bool

In [102]:
h = (a==2)
print(h)
type(h)
# 0 é false

False


bool

In [103]:
i = True
type(i)
# true e false são boleanos

bool

In [104]:
ii = 'True'
type(ii)
# quando está entre '' será string de texto (mesmo escrito true ou false)

str

## Operação de comparação

In [105]:
# Operação ==
a==b
#igualdade

True

In [106]:
# Operação ><
a>b
#maior ou menor

False

In [107]:
# Operação !=
a!=b
#diferença

False

In [108]:
# Operação >= ou <=
a>=b
#maior ou igual a / menor ou igual a

True

## Operações matemáticas

In [109]:
# Soma 
a+b
#soma é +

2.0

In [110]:
# Soma e atribui valor
ab = a+b
print(ab)
# da pra atribuir variáveis a partir de operações em outras existentes

2.0


In [111]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)
# multiplicação por *

Não use l como nome de variável
1.0


In [112]:
# Divisão
a/b
#divisão por /

1.0

In [113]:
# Potencia
5**2
#potência por ** ao invés de ^

25

In [114]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)
# quando estamos usando bibliotecas da pra usar outras operações como exponencial

22026.465794806718

In [115]:
math.exp(0)
#exponencial de 0

1.0

In [116]:
math.exp(a)
#da pra usar operação de biblioteca nas variáveis

2.718281828459045

In [117]:
math.exp(-10)
#dá pra usar numeros negativos apenas com - na frente

4.5399929762484854e-05

In [118]:
import math as mt
mt.log(c)
#diminuindo nome da biblioteca pra usar mais rapido

0.0

In [119]:
mt.log10(100)
#alem de exponencial, a biblioteca math tem log10

2.0

## Listas

In [120]:
myFirstList = [1,2,3]
print(myFirstList)
#criando listas que guardam valores ordenados

[1, 2, 3]


In [121]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])
#como acessar cada valor pelo index

1
3


In [122]:
myFirstList==a
#comparação da lista com variável

False

In [123]:
myFirstList[0]==a
#comparação de UM dos valores da lista com variável

True

In [124]:
mySecList = [1,a,'c']
print(mySecList)
# dá pra usar variáveis e str nas listas

[1, 1, 'c']


In [125]:
type(mySecList)
#tipo da lista

list

In [126]:
type(mySecList[2])
#tipo do valor dentro da lista

str

In [127]:
type(mySecList[1])
#tipo do valor dentro da lista
#lembrar de acessar pelo index usando []

int

## Caminhos = path

In [128]:
path = r"C:\UFSC\ENS410064"
print(path)
#a diferença do uso do "r" aqui e na variável de baixo faz diferença porque faz com que a barra invertida seguida de caracteres seja interpretada \ 
# string ao invés de caracteres de escape

C:\UFSC\ENS410064


In [129]:
path = "C:/UFSC/ENS410064"
print(path)

C:/UFSC/ENS410064


In [130]:
import os
# Listar arquivos na pasta
os.listdir(path)
#listando os arquivos e pastas que vem no diretorio

['.git', '.gitignore', 'README.md', 'scripts', 'venv']

In [131]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]
#usando o index para chegar nos arquivos da pasta

'.git'

In [132]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]
#"criando" diretorio

'C:/UFSC/ENS410064/.git'

In [133]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])
# vendo arquivos da pasta "nova"

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [134]:
# Diretório que estou trababalhando
os.getcwd()
#serve pra verificar em que pasta estou trabalhando
#cwd = currently working directory

'C:\\UFSC'

In [135]:
# Mudo de diretório para o caminho 
os.chdir(r'C:\UFSC')
#chdir = change directory

In [136]:
os.getcwd()
#mostrando que mudou o diretório

'C:\\UFSC'

In [137]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
#primeiro verificando se o novo diretorio existe com os.path.isdir
#depois criando diretorio com os.mkdir

diretório já existe


In [138]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
#criando pasta com arquivo de texto e escrevendo dentro do txt

diretório já existe


## Numpy arrays e Pandas DataFrames

In [139]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)
#n é uma variável array com um unico valor, 0

numpy.ndarray

In [140]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)
#cria um array com valores de lista existente

[ 1  2  3 10 20 55]


In [141]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)
#n.shape tamanho da matriz
#em matriz (x,y) será o numero de linhas e colunas

[[0.91279195 0.47968881 0.34433484 0.53713881 0.11921209 0.30228909
  0.84260348 0.53919793 0.89164547 0.01041802]
 [0.40618021 0.02346861 0.57592133 0.29732176 0.55980616 0.54539698
  0.06627965 0.89265006 0.34275758 0.14113403]
 [0.93804064 0.95802436 0.97000259 0.07810503 0.66809655 0.68013237
  0.23216005 0.58259583 0.0903162  0.07301439]
 [0.46659292 0.16516484 0.59417955 0.46324832 0.56825658 0.27615594
  0.22154584 0.21796378 0.36573678 0.46217649]
 [0.55372129 0.60066187 0.0114947  0.91730727 0.14787211 0.01134488
  0.70287857 0.5224087  0.27847455 0.99306953]
 [0.86518861 0.23703811 0.13295017 0.16371537 0.46290343 0.42738757
  0.19606139 0.05113591 0.42005325 0.81899035]
 [0.44823355 0.58564832 0.62139929 0.57366965 0.85956054 0.55055972
  0.87127688 0.66857639 0.20150657 0.1396075 ]
 [0.54311799 0.09284242 0.87837486 0.76756304 0.61939656 0.54514977
  0.83723345 0.87788661 0.29344767 0.4895825 ]
 [0.60122708 0.73997643 0.92256128 0.81661515 0.72400497 0.19698872
  0.47206582

In [142]:
# Acessando valores da matriz
n[0,:]
#acessando a primeira linha toda da matriz por slicing

array([0.91279195, 0.47968881, 0.34433484, 0.53713881, 0.11921209,
       0.30228909, 0.84260348, 0.53919793, 0.89164547, 0.01041802])

In [143]:
n[:,0]
#acessando a primeira coluna por slicing

array([0.91279195, 0.40618021, 0.93804064, 0.46659292, 0.55372129,
       0.86518861, 0.44823355, 0.54311799, 0.60122708, 0.4844916 ])

In [144]:
n[:,1:5]
#acessando os valores das colunas 2,3,4,5 e 6 de todas as linhas
#lembrar que o index começa em 0

array([[0.47968881, 0.34433484, 0.53713881, 0.11921209],
       [0.02346861, 0.57592133, 0.29732176, 0.55980616],
       [0.95802436, 0.97000259, 0.07810503, 0.66809655],
       [0.16516484, 0.59417955, 0.46324832, 0.56825658],
       [0.60066187, 0.0114947 , 0.91730727, 0.14787211],
       [0.23703811, 0.13295017, 0.16371537, 0.46290343],
       [0.58564832, 0.62139929, 0.57366965, 0.85956054],
       [0.09284242, 0.87837486, 0.76756304, 0.61939656],
       [0.73997643, 0.92256128, 0.81661515, 0.72400497],
       [0.46377384, 0.68515421, 0.08765051, 0.99866245]])

In [145]:
n[0,1:5]
#fazendo o mesmo que antes só que só pra primeira linha

array([0.47968881, 0.34433484, 0.53713881, 0.11921209])

In [146]:
n[0,-1]
#acessando valor da primeira linha e ultima coluna usando sinal negativo ao invés de 9

0.010418016982163825

In [147]:
n[0,4:-1]
#acessando valores

array([0.11921209, 0.30228909, 0.84260348, 0.53919793, 0.89164547])

In [148]:
n[0,4:]
#usando : como um "até" da coluna 4 até a última

array([0.11921209, 0.30228909, 0.84260348, 0.53919793, 0.89164547,
       0.01041802])

In [149]:
an = np.log(n*5)
print(an)
#usando operação nos valores da matriz

[[ 1.51819061  0.87482021  0.54329719  0.98793918 -0.51741318  0.41306646
   1.43817911  0.99176536  1.49475123 -2.95478066]
 [ 0.70847957 -2.14265355  1.0576537   0.39649755  1.02927321  1.00319657
  -1.10443451  1.49587726  0.53870606 -0.34860738]
 [ 1.54547591  1.56655584  1.57898138 -0.94026288  1.20611534  1.22397008
   0.14910963  1.06917631 -0.7950005  -1.00766077]
 [ 0.84713981 -0.19137337  1.08886418  0.83994588  1.04425568  0.32264835
   0.10231215  0.08601155  0.60359652  0.83762946]
 [ 1.0183441   1.0997148  -2.85643138  1.52312513 -0.30196959 -2.86955121
   1.25686678  0.96013286  0.33100929  1.60248332]
 [ 1.46463017  0.16990355 -0.40834298 -0.200188    0.83920108  0.75937389
  -0.01988954 -1.36383032  0.74206412  1.40975493]
 [ 0.80699705  1.0744021   1.1336565   1.05373633  1.45810389  1.01261808
   1.47164245  1.20683329  0.00750461 -0.35948242]
 [ 0.99900923 -0.76741368  1.47975608  1.34490324  1.13042835  1.0027432
   1.43178558  1.47920007  0.38338197  0.89523563]
 